### ISSUE TITLE
LPF audiobook should have publication.json at root of zip directory (not inside subfolder)

### ISSUE THREAD

**Issue by danielweck** [w3c/publ-tests#36]
(if I am not mistaken)

`Lang_Crimson_Fairy_Book.lpf`
downloaded from:
https://github.com/w3c/publ-tests/tree/master/test_content/audiobooks
=>
`/Lang_Crimson_Fairy_Book/publication.json`
should be:
`/publication.json`

**Comment by iherman** [comment]
Cc @wareid

**Comment by wareid** [comment]
Should be fixed by 92fea84 

I rezipped what I had in my folder, which seems to have worked elsewhere. Let me know if it is still a problem.

**Comment by danielweck** [comment]
Thanks! :)

Unfortunately:

https://drive.google.com/open?id=1WKeBMd9FTjRnTrGl3iyOuQEfDdV0MQja

> You need permission
> Want in? Ask for access, or switch to an account with permission.

**Comment by wareid** [comment]
Should be fixed now :)

**Comment by danielweck** [comment]
I am afraid the problem persists. The zip archive contains an extraneous top-level folder. If I am not mistaken, `publication.json` should be located at the root of the ZIP directory.

**Comment by danielweck** [comment]
Specification references (for my own records):
https://www.w3.org/TR/lpf/#sec-structure
https://w3c.github.io/lpf/#sec-structure

**Comment by danielweck** [comment]
Related issue: https://github.com/w3c/publ-tests/issues/40
